"""add_transferencias_notificacoes_pedidos_peca

Revision ID: 4a8e8944f309
Revises: 6b2f6cadbc04
Create Date: 2026-05-15 22:52:37.453838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '4a8e8944f309'
down_revision: Union[str, None] = '6b2f6cadbc04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notificacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('utilizador_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('PEDIDO_PECA', 'PEDIDO_TRANSFERENCIA', 'TRANSFERENCIA_ACEITE', 'TRANSFERENCIA_RECUSADA', 'TRANSFERENCIA_CONCLUIDA', 'PECA_APROVADA', 'PECA_RECUSADA', name='tiponotificacao'), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('mensagem', sa.String(length=1000), nullable=False),
    sa.Column('lida', sa.Boolean(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.Column('referencia_id', sa.Integer(), nullable=True),
    sa.Column('referencia_tipo', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['utilizador_id'], ['utilizadores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pedidos_transferencia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=50), nullable=False),
    sa.Column('loja_origem_id', sa.Integer(), nullable=False),
    sa.Column('loja_destino_id', sa.Integer(), nullable=False),
    sa.Column('gerente_origem_id', sa.Integer(), nullable=False),
    sa.Column('gerente_destino_id', sa.Integer(), nullable=False),
    sa.Column('peca_id', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('estado', sa.Enum('PENDENTE', 'ACEITE', 'CONCLUIDA', 'RECUSADO', 'CANCELADO', name='estadopedidotransferencia'), nullable=False),
    sa.Column('data_pedido', sa.DateTime(), nullable=False),
    sa.Column('data_resposta', sa.DateTime(), nullable=True),
    sa.Column('data_recepcao', sa.DateTime(), nullable=True),
    sa.Column('data_assinatura_origem', sa.DateTime(), nullable=True),
    sa.Column('data_assinatura_destino', sa.DateTime(), nullable=True),
    sa.Column('observacoes_pedido', sa.String(length=500), nullable=True),
    sa.Column('observacoes_resposta', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['gerente_destino_id'], ['utilizadores.id'], ),
    sa.ForeignKeyConstraint(['gerente_origem_id'], ['utilizadores.id'], ),
    sa.ForeignKeyConstraint(['loja_destino_id'], ['lojas.id'], ),
    sa.ForeignKeyConstraint(['loja_origem_id'], ['lojas.id'], ),
    sa.ForeignKeyConstraint(['peca_id'], ['pecas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero')
    )
    op.create_table('pedidos_peca',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ordem_servico_id', sa.Integer(), nullable=False),
    sa.Column('mecanico_id', sa.Integer(), nullable=False),
    sa.Column('loja_id', sa.Integer(), nullable=False),
    sa.Column('peca_id', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('estado', sa.Enum('PENDENTE', 'APROVADO', 'RECUSADO', name='estadopedidopeca'), nullable=False),
    sa.Column('data_pedido', sa.DateTime(), nullable=False),
    sa.Column('data_resposta', sa.DateTime(), nullable=True),
    sa.Column('observacoes', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['loja_id'], ['lojas.id'], ),
    sa.ForeignKeyConstraint(['mecanico_id'], ['utilizadores.id'], ),
    sa.ForeignKeyConstraint(['ordem_servico_id'], ['ordens_servico.id'], ),
    sa.ForeignKeyConstraint(['peca_id'], ['pecas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pedidos_peca')
    op.drop_table('pedidos_transferencia')
    op.drop_table('notificacoes')
    # ### end Alembic commands ###
