"""initial

Revision ID: 6b2f6cadbc04
Revises: 
Create Date: 2026-05-15 21:58:26.979871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '6b2f6cadbc04'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lojas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('cidade', sa.String(length=100), nullable=False),
    sa.Column('morada', sa.String(length=255), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pecas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('referencia', sa.String(length=50), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('categoria', sa.Enum('BATERIA', 'PNEU', 'TRAVAO', 'MOTOR', 'CONTROLADOR', 'LUZ', 'ACESSORIO', 'OUTRO', name='categoriapeca'), nullable=False),
    sa.Column('descricao', sa.String(length=500), nullable=True),
    sa.Column('unidade', sa.String(length=50), nullable=False),
    sa.Column('preco_custo', sa.Float(), nullable=False),
    sa.Column('preco_venda', sa.Float(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('referencia')
    )
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('nif', sa.String(length=9), nullable=False),
    sa.Column('telemovel', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('morada', sa.String(length=255), nullable=True),
    sa.Column('consentimento_rgpd', sa.Boolean(), nullable=False),
    sa.Column('data_registo', sa.DateTime(), nullable=False),
    sa.Column('loja_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['loja_id'], ['lojas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nif')
    )
    op.create_table('stock_lojas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('peca_id', sa.Integer(), nullable=False),
    sa.Column('loja_id', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('limite_minimo', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['loja_id'], ['lojas.id'], ),
    sa.ForeignKeyConstraint(['peca_id'], ['pecas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('utilizadores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('perfil', sa.Enum('ADMINISTRADOR', 'GERENTE_LOJA', 'RECECIONISTA', 'MECANICO', name='perfilutilizador'), nullable=False),
    sa.Column('loja_id', sa.Integer(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('comissao', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['loja_id'], ['lojas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('auditoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evento', sa.Enum('LOGIN_SUCESSO', 'LOGIN_FALHA', 'ACESSO_NEGADO', 'OS_ESTADO_ALTERADO', 'STOCK_ENTRADA', 'STOCK_TRANSFERENCIA', 'FATURA_EMITIDA', name='tipoeventoauditoria'), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=False),
    sa.Column('utilizador_id', sa.Integer(), nullable=True),
    sa.Column('loja_id', sa.Integer(), nullable=True),
    sa.Column('ip_origem', sa.String(length=50), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('detalhe', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['loja_id'], ['lojas.id'], ),
    sa.ForeignKeyConstraint(['utilizador_id'], ['utilizadores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trotinetes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('marca', sa.String(length=100), nullable=False),
    sa.Column('modelo', sa.String(length=100), nullable=False),
    sa.Column('numero_serie', sa.String(length=100), nullable=False),
    sa.Column('ano_compra', sa.Integer(), nullable=True),
    sa.Column('cor', sa.String(length=50), nullable=True),
    sa.Column('observacoes_tecnicas', sa.String(length=500), nullable=True),
    sa.Column('data_registo', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_serie')
    )
    op.create_table('ordens_servico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=50), nullable=False),
    sa.Column('trotinete_id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('loja_id', sa.Integer(), nullable=False),
    sa.Column('mecanico_id', sa.Integer(), nullable=True),
    sa.Column('estado', sa.Enum('PENDENTE', 'EM_DIAGNOSTICO', 'AGUARDA_APROVACAO', 'EM_REPARACAO', 'AGUARDA_PECAS', 'CONCLUIDA', 'FATURADA', 'CANCELADA', name='estadoordemservico'), nullable=False),
    sa.Column('prioridade', sa.Enum('BAIXA', 'NORMAL', 'ALTA', 'URGENTE', name='prioridadeordemservico'), nullable=False),
    sa.Column('descricao_problema', sa.String(length=1000), nullable=False),
    sa.Column('preco_servico', sa.Float(), nullable=False),
    sa.Column('data_entrada', sa.DateTime(), nullable=False),
    sa.Column('data_conclusao', sa.DateTime(), nullable=True),
    sa.Column('tempo_total_minutos', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['loja_id'], ['lojas.id'], ),
    sa.ForeignKeyConstraint(['mecanico_id'], ['utilizadores.id'], ),
    sa.ForeignKeyConstraint(['trotinete_id'], ['trotinetes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero')
    )
    op.create_table('faturas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=50), nullable=False),
    sa.Column('ordem_servico_id', sa.Integer(), nullable=False),
    sa.Column('data_emissao', sa.DateTime(), nullable=False),
    sa.Column('estado', sa.Enum('EMITIDA', 'ANULADA', name='estadofatura'), nullable=False),
    sa.Column('subtotal_pecas', sa.Float(), nullable=False),
    sa.Column('valor_final', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['ordem_servico_id'], ['ordens_servico.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero'),
    sa.UniqueConstraint('ordem_servico_id')
    )
    op.create_table('os_pecas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ordem_servico_id', sa.Integer(), nullable=False),
    sa.Column('peca_id', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('preco_venda_unitario', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['ordem_servico_id'], ['ordens_servico.id'], ),
    sa.ForeignKeyConstraint(['peca_id'], ['pecas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('registos_tempo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ordem_servico_id', sa.Integer(), nullable=False),
    sa.Column('inicio', sa.DateTime(), nullable=False),
    sa.Column('fim', sa.DateTime(), nullable=True),
    sa.Column('minutos_esta_sessao', sa.Integer(), nullable=True),
    sa.Column('tempo_total_acumulado_minutos', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ordem_servico_id'], ['ordens_servico.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('registos_tempo')
    op.drop_table('os_pecas')
    op.drop_table('faturas')
    op.drop_table('ordens_servico')
    op.drop_table('trotinetes')
    op.drop_table('auditoria')
    op.drop_table('utilizadores')
    op.drop_table('stock_lojas')
    op.drop_table('clientes')
    op.drop_table('pecas')
    op.drop_table('lojas')
    # ### end Alembic commands ###
